---
# Configuration for rubocop-rspec_rails

plugins:
  - rubocop-rspec_rails

################################################################################
#                              RSPEC/RAILS
################################################################################

RSpecRails/HttpStatus:
  Enabled: true
  EnforcedStyle: "numeric"
