---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  DisabledByDefault: false
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "**/bin/*"
    - "**/config.ru"
    - "**/db/**/*"
    - "**/node_modules/**/*"
    - "**/vendor/**/*"
    - "**/vendor/**/*.txt"
    - "**/test/**/*"
    - "**/tmp/**/*"

# Dim down rubocop's annoyance level below:

FactoryBot/SyntaxMethods:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/LineLength:
  Max: 125

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - and
    - as
    - for
    - if
    - in
    - or
    - unless
    - when
    - with
    - without

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# TODO: Consider if this is needed
RSpecRails/InferredSpecType:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - app/events/**/*.rb
    # - app/views/**/*.rb

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "()"
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
