---
name: Lint
on:
  - push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        timeout-minutes: 5
        with:
          fetch-depth: 0

      - name: Build Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --force-exclusion

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install YAMLLint
        run: pip install yamllint

      - name: Run YAMLLint
        run: yamllint -f github -d .yamllint .

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Remark
        run: |
          npm install -g \
            remark-cli \
            remark-preset-lint-consistent \
            remark-preset-lint-recommended \
            remark-preset-lint-markdown-style-guide

      - name: Run Remark
        run: remark --ignore-path .markdownlintignore --silently-ignore **/*.md .**/*.md
